### PR TITLE
update reitit to 0.3.1 for perf tests

### PR DESCRIPTION
**Pull request by ikitommi**
Released a faster version of reitit, updated here too for benchmarking purposes.

### CODE REVIEW

**Comment by kumarshantanu** [comment]
@ikitommi Sorry for a late turnaround. I recently started working on Calfpath again and have updated Reitit version to `0.5.5` (latest as of now) in perf benchmarks in the `v0.8.0` branch.

**Comment by ikitommi** [comment]
hi. could you copy the reitit router options `{:inject-match? false, :inject-router? false, :reitit.trie/parameters reitit.trie/record-parameters}` to the new branch from here. Closing this one. thanks.

**Comment by kumarshantanu** [comment]
When I try to add `:inject-match? false` I lose the ability to deduce the HTTP 405 response (no method match) scenario. Could you suggest any alternative?

**Comment by ikitommi** [comment]
top-level `:handler` catches all methods not explicitly declared, see https://github.com/ikitommi/calfpath/blob/2533656193cac2b7371aa87695e090969859d929/perf/calfpath/perf_test.clj#L131-L133

**Comment by kumarshantanu** [comment]
Thanks, I've added those params in the branch.

**Pull request closed without merging**
